connections:
  default:
    host: '192.168.1.17'
    port: 5672
    login: 'gamenet'
    password: 'MqHM21XJOj'
producers:
  user:
    connection: default
    exchange_options: {name: 'user_exchange', type: direct, durable: 0, passive: 0}
consumers:
  user:
    connection: default
    queue_options:
      name: 'user_queue'
      durable: 0
      autodelete: 0
      binding: {name: 'user_exchange', routing-keys: '*'}
    class: \Ko\Examples\ReceiverClass\Actions\HelloWorld