language: php

php:
  - 5.4
  - 5.5

services:
  - rabbitmq

install:
  - wget https://phar.phpunit.de/phpunit.phar

before_script:
  - composer install --no-dev
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - php phpunit.phar --verbose --coverage-text --configuration phpunit.xml