language: php

php:
  - 5.4
  - 5.5

services:
  - rabbitmq

install:
  composer install --no-dev

before_script:
  echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --verbose --coverage-text --configuration phpunit.xml